const catchAyncError = require("./catchAsyncError");

const isAuthenticatedUser = catchAsyncError(async(req, res, next)=>{

});